// Single source of truth for all provider metadata.
// Used by: config defaults, translate adapter routing, settings UI, popup UI.
const PROVIDERS = [
  {
    id: 'deepseek',
    name: 'DeepSeek',
    color: '#6366f1',
    desc: '国内大模型,翻译质量高,价格极低',
    adapter: 'openai-compat',
    enabled: true,
    apiKey: 'sk-b779edcb4e4b420a8431fe7e56688c82',
    endpoint: 'https://api.deepseek.com',
    model: 'deepseek-chat',
    models: ['deepseek-chat', 'deepseek-reasoner'],
    prompt: '请将以下{{src}}文本翻译为{{target}},仅输出译文,不要添加任何解释或注释',
    hasEndpoint: true,
    hasModel: true,
    hasSecret: false,
    hasRegion: false,
    hasPrompt: true,
    builtin: true
  },
  {
    id: 'bing',
    name: 'Bing 微软翻译',
    color: '#0891b2',
    desc: '国内直连稳定,免费额度较大',
    adapter: 'openai-compat',
    enabled: true,
    apiKey: '',
    endpoint: '',
    models: [],
    prompt: '请将以下文本翻译为{{target}},仅输出译文:',
    hasEndpoint: true,
    hasModel: false,
    hasSecret: false,
    hasRegion: true,
    region: 'eastasia',
    hasPrompt: false,
    builtin: true
  },
  {
    id: 'openai',
    name: 'OpenAI',
    color: '#059669',
    desc: 'GPT 系列模型,翻译质量高',
    adapter: 'openai-compat',
    enabled: true,
    apiKey: '',
    endpoint: '',
    model: 'gpt-4o-mini',
    models: ['gpt-4o', 'gpt-4o-mini', 'gpt-3.5-turbo'],
    prompt: '请将以下文本翻译为{{target}},仅输出译文:',
    hasEndpoint: true,
    hasModel: true,
    hasSecret: false,
    hasRegion: false,
    hasPrompt: true,
    builtin: false
  },
  {
    id: 'youdao',
    name: '有道翻译',
    color: '#ea580c',
    desc: '老牌,国内响应快,JWK 加密',
    adapter: 'youdao',
    enabled: false,
    apiKey: '',
    secret: '',
    models: [],
    prompt: '请将以下文本翻译为{{target}},仅输出译文:',
    hasEndpoint: false,
    hasModel: false,
    hasSecret: true,
    hasRegion: false,
    hasPrompt: false,
    builtin: false
  },
  {
    id: 'tencent',
    name: '腾讯交互翻译 TMT',
    color: '#7c3aed',
    desc: '腾讯云,国内节点,需 SecretId+SecretKey',
    adapter: 'tencent',
    enabled: false,
    apiKey: '',
    secret: '',
    models: [],
    prompt: '请将以下文本翻译为{{target}},仅输出译文:',
    hasEndpoint: false,
    hasModel: false,
    hasSecret: true,
    hasRegion: false,
    hasPrompt: false,
    builtin: false
  },
  {
    id: 'deepl',
    name: 'DeepL',
    color: '#2563eb',
    desc: '欧洲语言表现极佳,需海外网络',
    adapter: 'deepl',
    enabled: false,
    apiKey: '',
    models: [],
    prompt: '请将以下文本翻译为{{target}},仅输出译文:',
    hasEndpoint: false,
    hasModel: false,
    hasSecret: false,
    hasRegion: false,
    hasPrompt: false,
    builtin: false
  },
  {
    id: 'caiyun',
    name: '彩云小译',
    color: '#d97706',
    desc: '中日翻译流畅,中文母语优化',
    adapter: 'caiyun',
    enabled: false,
    apiKey: '',
    models: [],
    prompt: '请将以下文本翻译为{{target}},仅输出译文:',
    hasEndpoint: false,
    hasModel: false,
    hasSecret: false,
    hasRegion: false,
    hasPrompt: false,
    builtin: false
  },
  {
    id: 'baidu',
    name: '百度翻译',
    color: '#dc2626',
    desc: 'appid + 密钥,免费额度充足',
    adapter: 'baidu',
    enabled: false,
    apiKey: '',
    secret: '',
    models: [],
    prompt: '请将以下文本翻译为{{target}},仅输出译文:',
    hasEndpoint: false,
    hasModel: false,
    hasSecret: true,
    hasRegion: false,
    hasPrompt: false,
    builtin: false
  },
  {
    id: 'google',
    name: 'Google 翻译',
    color: '#db2777',
    desc: '官方 API,语种最全,国内不可直达',
    adapter: 'openai-compat',
    enabled: false,
    apiKey: '',
    models: [],
    prompt: '请将以下文本翻译为{{target}},仅输出译文:',
    hasEndpoint: false,
    hasModel: false,
    hasSecret: false,
    hasRegion: false,
    hasPrompt: false,
    builtin: false
  }
]

// Build a lookup map: id → provider metadata
const byId = {}
for (const p of PROVIDERS) byId[p.id] = p

function getProvider(id) { return byId[id] }
function getAll() { return PROVIDERS }

module.exports = { PROVIDERS, getProvider, getAll }